// tailwind.config.ts
// Generated by anydesign for Vercel landing (vercel.com)
// Source: DTCG design-tokens.json

import type { Config } from 'tailwindcss';

const config: Config = {
  content: ['./src/**/*.{html,js,jsx,ts,tsx}'],
  theme: {
    extend: {
      colors: {
        "background": {
          "100": "#FFFFFF",
          "200": "#FAFAFA"
        },
        "gray": {
          "100": "#F2F2F2",
          "200": "#EBEBEB",
          "300": "#E6E6E6",
          "400": "#EAEAEA",
          "500": "#C9C9C9",
          "600": "#A8A8A8",
          "700": "#8F8F8F",
          "800": "#7D7D7D",
          "900": "#4D4D4D",
          "1000": "#171717"
        },
        "gray-alpha": {
          "100": "#0000000d",
          "200": "#00000015",
          "300": "#0000001a",
          "400": "#00000014",
          "500": "#00000036",
          "600": "#0000003d",
          "700": "#00000070",
          "800": "#00000082",
          "900": "#000000b3",
          "1000": "#000000e8"
        },
        "blue": {
          "100": "#F0F7FF",
          "200": "#EAF4FF",
          "300": "#E0EFFF",
          "400": "#CCE7FF",
          "500": "#97CCFF",
          "600": "#51AEFF",
          "700": "#0070F7",
          "800": "#005EDC",
          "900": "#0064E2",
          "1000": "#002453"
        },
        "red": {
          "100": "#FFEEF0",
          "200": "#FFE9EA",
          "300": "#FFE4E5",
          "400": "#FFD8D7",
          "500": "#FFB5B6",
          "600": "#FF6A6E",
          "700": "#FC0035",
          "800": "#E70022",
          "900": "#D60020",
          "1000": "#46000C"
        },
        "amber": {
          "100": "#FFF6E1",
          "200": "#FFF4D4",
          "300": "#FFF1C8",
          "400": "#FFDD84",
          "500": "#FFC85E",
          "600": "#FFAA00",
          "700": "#FFB200",
          "800": "#FF9900",
          "900": "#A64F00",
          "1000": "#541C00"
        },
        "green": {
          "100": "#ECFDEC",
          "200": "#E5FCE7",
          "300": "#D3FAD1",
          "400": "#B9F5BC",
          "500": "#82EB8D",
          "600": "#4CE15E",
          "700": "#28A948",
          "800": "#279141",
          "900": "#107D32",
          "1000": "#00370D"
        },
        "teal": {
          "100": "#DFFFFB",
          "200": "#DDFEF6",
          "300": "#CCF9F1",
          "400": "#B1F7EC",
          "500": "#52F0DB",
          "600": "#00E2C4",
          "700": "#00A694",
          "800": "#008D7D",
          "900": "#007A6E",
          "1000": "#003D34"
        },
        "purple": {
          "100": "#F9F0FF",
          "200": "#F9F1FF",
          "300": "#F5E8FF",
          "400": "#F1D9FF",
          "500": "#DDA9FF",
          "600": "#C77DFF",
          "700": "#9F00F4",
          "800": "#8400CD",
          "900": "#7C00C9",
          "1000": "#2E004D"
        },
        "pink": {
          "100": "#FFEAF5",
          "200": "#FFEAF2",
          "300": "#FFE0EB",
          "400": "#FFD5E1",
          "500": "#FDB3CC",
          "600": "#F97EA7",
          "700": "#F22782",
          "800": "#E4106E",
          "900": "#C41562",
          "1000": "#460523"
        },
        "marketing": {
          "background": "#FAFBFC",
          "violet": "#7928CA",
          "cyan": "#50E3C2",
          "highlight-pink": "#FF0080"
        }
      },
      fontFamily: {
        "sans": ["ui-sans-serif", "system-ui", "Noto Sans SC", "PingFang SC", "Hiragino Sans GB", "Microsoft YaHei", "sans-serif"],
        "mono": ["ui-monospace", "SFMono-Regular", "Menlo", "Monaco", "Consolas", "'Liberation Mono'", "Noto Sans Mono CJK SC", "PingFang SC", "monospace"]
      },
      fontSize: {
        "xs": "0.75rem",
        "sm": "0.875rem",
        "base": "1rem",
        "lg": "1.125rem",
        "xl": "1.25rem",
        "2xl": "1.5rem",
        "3xl": "1.875rem",
        "5xl": "3rem"
      },
      fontWeight: {
        "thin": "100",
        "light": "300",
        "normal": "400",
        "medium": "500",
        "semibold": "600",
        "bold": "700",
        "extrabold": "800"
      },
      lineHeight: {
        "tight": "1.25",
        "normal": "1.5",
        "relaxed": "1.625"
      },
      letterSpacing: {
        "tighter": "-0.05em",
        "tight": "-0.025em",
        "normal": "0em"
      },
      spacing: {
        "base": "4px",
        "2x": "8px",
        "3x": "12px",
        "4x": "16px",
        "6x": "24px",
        "8x": "32px",
        "10x": "40px",
        "16x": "64px",
        "24x": "96px",
        "32x": "128px",
        "48x": "192px",
        "64x": "256px"
      },
      borderRadius: {
        "default": "6px",
        "marketing": "8px",
        "code-block": "6px",
        "modal": "12px",
        "3xl": "1.5rem"
      },
      boxShadow: {
        "2xs": "0px 1px 1px #0000000a",
        "xs": "0px 1px 2px #0000000a",
        "small": "0px 2px 2px #0000000a",
        "medium": "0px 2px 2px #0000000a, 0px 8px 8px -8px #0000000a",
        "large": "0px 2px 2px #0000000a, 0px 8px 16px -4px #0000000a",
        "xl": "0px 1px 1px #00000005, 0px 4px 8px -4px #0000000a, 0px 16px 24px -8px #0000000f",
        "2xl": "0px 1px 1px #00000005, 0px 8px 16px -4px #0000000a, 0px 24px 32px -8px #0000000f"
      },
    },
  },
};

export default config;
